---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keystore-config-miner01
  namespace: default
  labels:
    app: miner
    name: keystore-config-miner01
data:
  UTC--2019-06-04T13-52-41.551926270Z--c11ba4c7c24f70e7a581c7daa92eac108099acec: |-
    {
      "address": "c11ba4c7c24f70e7a581c7daa92eac108099acec",
      "crypto": {
        "cipher": "aes-128-ctr",
        "ciphertext": "5ae07c505387815200c9e8e29afcd0d48d0d9a9e5f2c621f29cc2eec129e0998",
        "cipherparams": {
          "iv": "f306175b1583237547649168940bd0a9"
        },
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 32,
          "n": 262144,
          "p": 1,
          "r": 8,
          "salt": "eb4d2437d9a8401a4fc0e28ccf35d0375e917d54563cbe2d19b17feca2b4241b"
        },
        "mac": "45c85951c3b76a4ae6b68638997f46fae8330c5a17791a7b21d903b72e10756e"
      },
      "id": "f092bb3c-0294-449c-ae63-b0b6d9b122ef",
      "version": 3
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keystore-config-miner02
  namespace: default
  labels:
    app: miner
    name: keystore-config-miner02
data:
  UTC--2019-06-04T13-52-48.511656735Z--4c92786b90d848eaa3f4ef46918af724a309ae79: |-
    {
      "address": "4c92786b90d848eaa3f4ef46918af724a309ae79",
      "crypto": {
        "cipher": "aes-128-ctr",
        "ciphertext": "bce6942b7494a5a1e727367f38103524c4337957505a80c7cdefa041c6f732b5",
        "cipherparams": {
          "iv": "cbe64393b063d05d437fb346c07874c9"
        },
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 32,
          "n": 262144,
          "p": 1,
          "r": 8,
          "salt": "492c776c50bb1e3caf02e4006838957b5fb500b22c7ef980d237f67bd5d3b8ec"
        },
        "mac": "97f142a72c94a828046b48f277db9a4ab3fe5048df5473b3202cc5c01a0cf6be"
      },
      "id": "edfd188b-2962-400e-b121-78e866e8e29e",
      "version": 3
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keystore-config-miner03
  namespace: default
  labels:
    app: miner
    name: keystore-config-miner03
data:
  UTC--2019-06-04T13-52-53.567362092Z--4e7afbdc9413eeb582b3f1be49d652fa714484da: |-
    {
      "address": "4e7afbdc9413eeb582b3f1be49d652fa714484da",
      "crypto": {
        "cipher": "aes-128-ctr",
        "ciphertext": "12bb86756bc1503fcba1f6329ae2827a2cdf7c9bb8b4061c9635eacfeb7d6439",
        "cipherparams": {
          "iv": "b65d1c691a15673d989cc630ffbbeb65"
        },
        "kdf": "scrypt",
        "kdfparams": {
          "dklen": 32,
          "n": 262144,
          "p": 1,
          "r": 8,
          "salt": "67bfce9b064e92f06ccd71d7f3262eb22133a044fb71c90cd8bd4dfca0e56e6c"
        },
        "mac": "b9fe62415d74553629bbbfe1ca7137e172cfb2adba5f87b0599216dfd980173a"
      },
      "id": "d6a4404e-8f63-4d5b-bb79-14564db8931c",
      "version": 3
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gethconfig-miner01
  namespace: default
  labels:
    app: miner
    name: gethconfig-miner01
data:
  gethconfig: |-
    [Eth]
    NetworkId = 123456
    SyncMode = "full"
    LightPeers = 100
    DatabaseCache = 768
    Etherbase = "0xc11ba4c7c24f70e7a581c7daa92eac108099acec"
    MinerGasPrice = 0
    EnablePreimageRecording = false
    
    [Eth.Ethash]
    CacheDir = "ethash"
    CachesInMem = 2
    CachesOnDisk = 3
    DatasetDir = "/root/.ethash"
    DatasetsInMem = 1
    DatasetsOnDisk = 2
    PowMode = 0
    
    [Eth.TxPool]
    Locals = []
    NoLocals = false
    Journal = "transactions.rlp"
    Rejournal = 3600000000000
    PriceLimit = 1
    PriceBump = 10
    AccountSlots = 16
    GlobalSlots = 4096
    AccountQueue = 64
    GlobalQueue = 1024
    Lifetime = 10800000000000
    
    [Eth.GPO]
    Blocks = 20
    Percentile = 60
    
    [Shh]
    MaxMessageSize = 1048576
    MinimumAcceptedPOW = 2e-01
    
    [Node]
    UserIdent = "miner01"
    DataDir = "/etc/testnet/miner01"
    IPCPath = "/etc/testnet/miner01/geth.ipc"
    HTTPHost = "0.0.0.0"
    HTTPPort = 8545
    HTTPCors = ["*"]
    HTTPVirtualHosts = ["*"]
    HTTPModules = ["db", "eth", "net", "web3", "personal", "miner", "admin", "clique"]
    WSHost = "0.0.0.0"
    WSPort = 8546
    WSOrigins = ["*"]
    WSModules = ["net", "web3", "eth", "shh"]
    
    [Node.P2P]
    MaxPeers = 25
    NoDiscovery = false
    BootstrapNodes = []
    BootstrapNodesV5 = []
    StaticNodes = []
    TrustedNodes = []
    ListenAddr = ":30303"
    EnableMsgEvents = false
    
    [Dashboard]
    Host = "0.0.0.0"
    Port = 8080
    Refresh = 3000000000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gethconfig-miner02
  namespace: default
  labels:
    app: miner
    name: gethconfig-miner02
data:
  gethconfig: |-
    [Eth]
    NetworkId = 123456
    SyncMode = "full"
    LightPeers = 100
    DatabaseCache = 768
    Etherbase = "0x4c92786b90d848eaa3f4ef46918af724a309ae79"
    MinerGasPrice = 0
    EnablePreimageRecording = false
    
    [Eth.Ethash]
    CacheDir = "ethash"
    CachesInMem = 2
    CachesOnDisk = 3
    DatasetDir = "/root/.ethash"
    DatasetsInMem = 1
    DatasetsOnDisk = 2
    PowMode = 0
    
    [Eth.TxPool]
    Locals = []
    NoLocals = false
    Journal = "transactions.rlp"
    Rejournal = 3600000000000
    PriceLimit = 1
    PriceBump = 10
    AccountSlots = 16
    GlobalSlots = 4096
    AccountQueue = 64
    GlobalQueue = 1024
    Lifetime = 10800000000000
    
    [Eth.GPO]
    Blocks = 20
    Percentile = 60
    
    [Shh]
    MaxMessageSize = 1048576
    MinimumAcceptedPOW = 2e-01
    
    [Node]
    UserIdent = "miner02"
    DataDir = "/etc/testnet/miner02"
    IPCPath = "/etc/testnet/miner02/geth.ipc"
    HTTPHost = "0.0.0.0"
    HTTPPort = 8545
    HTTPCors = ["*"]
    HTTPVirtualHosts = ["*"]
    HTTPModules = ["db", "eth", "net", "web3", "personal", "miner", "admin", "clique"]
    WSHost = "0.0.0.0"
    WSPort = 8546
    WSOrigins = ["*"]
    WSModules = ["net", "web3", "eth", "shh"]
    
    [Node.P2P]
    MaxPeers = 25
    NoDiscovery = false
    BootstrapNodes = []
    BootstrapNodesV5 = []
    StaticNodes = []
    TrustedNodes = []
    ListenAddr = ":30303"
    EnableMsgEvents = false
    
    [Dashboard]
    Host = "0.0.0.0"
    Port = 8080
    Refresh = 3000000000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gethconfig-miner03
  namespace: default
  labels:
    app: miner
    name: gethconfig-miner03
data:
  gethconfig: |-
    [Eth]
    NetworkId = 123456
    SyncMode = "full"
    LightPeers = 100
    DatabaseCache = 768
    Etherbase = "0x4e7afbdc9413eeb582b3f1be49d652fa714484da"
    MinerGasPrice = 0
    EnablePreimageRecording = false
    
    [Eth.Ethash]
    CacheDir = "ethash"
    CachesInMem = 2
    CachesOnDisk = 3
    DatasetDir = "/root/.ethash"
    DatasetsInMem = 1
    DatasetsOnDisk = 2
    PowMode = 0
    
    [Eth.TxPool]
    Locals = []
    NoLocals = false
    Journal = "transactions.rlp"
    Rejournal = 3600000000000
    PriceLimit = 1
    PriceBump = 10
    AccountSlots = 16
    GlobalSlots = 4096
    AccountQueue = 64
    GlobalQueue = 1024
    Lifetime = 10800000000000
    
    [Eth.GPO]
    Blocks = 20
    Percentile = 60
    
    [Shh]
    MaxMessageSize = 1048576
    MinimumAcceptedPOW = 2e-01
    
    [Node]
    UserIdent = "miner03"
    DataDir = "/etc/testnet/miner03"
    IPCPath = "/etc/testnet/miner03/geth.ipc"
    HTTPHost = "0.0.0.0"
    HTTPPort = 8545
    HTTPCors = ["*"]
    HTTPVirtualHosts = ["*"]
    HTTPModules = ["db", "eth", "net", "web3", "personal", "miner", "admin", "clique"]
    WSHost = "0.0.0.0"
    WSPort = 8546
    WSOrigins = ["*"]
    WSModules = ["net", "web3", "eth", "shh"]
    
    [Node.P2P]
    MaxPeers = 25
    NoDiscovery = false
    BootstrapNodes = []
    BootstrapNodesV5 = []
    StaticNodes = []
    TrustedNodes = []
    ListenAddr = ":30303"
    EnableMsgEvents = false
    
    [Dashboard]
    Host = "0.0.0.0"
    Port = 8080
    Refresh = 3000000000

---
apiVersion: v1
kind: Service
metadata:
  name: miner01-svc
  namespace: default
  labels:
    app: miner
    tier: backend
    name: miner01-svc
spec:
  selector:
    app: miner
    tier: backend
    name: miner01
  ports:
    - name: miner01-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: miner01-wsrpc
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: miner01-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: miner01-dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: miner02-svc
  namespace: default
  labels:
    app: miner
    tier: backend
    name: miner02-svc
spec:
  selector:
    app: miner
    tier: backend
    name: miner02
  ports:
    - name: miner02-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: miner02-wsrpc
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: miner02-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: miner02-dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: miner03-svc
  namespace: default
  labels:
    app: miner
    tier: backend
    name: miner03-svc
spec:
  selector:
    app: miner
    tier: backend
    name: miner03
  ports:
    - name: miner03-jsonrpc
      protocol: TCP
      port: 8545
      targetPort: 8545
    - name: miner03-wsrpc
      protocol: TCP
      port: 8546
      targetPort: 8546
    - name: miner03-ipc-discovery
      protocol: TCP
      port: 30303
      targetPort: 30303
    - name: miner03-dashboard
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  labels:
    app: miner
    tier: backend
    name: geth-miner01
  name: geth-miner01
spec:
  selector:
    matchLabels:
      app: miner
  replicas: 1
  serviceName: geth-miner01
  template:
    metadata:
      name: geth-miner01
      labels:
        app: miner
        tier: backend
        name: miner01
    spec:
      containers:
      - name: miner01-container
        image: ethereum/client-go:v1.8.27
        imagePullPolicy: Always
        command: [ "sh" ]
        args:
        - "-cx"
        - "/usr/local/bin/geth --datadir /etc/testnet/miner01 init /etc/geth/genesis/genesis-geth.json;
           touch /etc/testnet/miner01/genesis_created;
           echo 123 > /etc/testnet/miner01/password.txt;
           mkdir -p /etc/geth/miner01;
           cp /etc/gethconfigmap/miner01/gethconfig.toml /etc/geth/miner01;
           ENODE=$(cat /etc/testnet/bootnode/enode.address);
           ENODE_ESC=$(echo $ENODE | sed 's@//@\\\\/\\\\/@g');
           sed -i \"s/BootstrapNodes = \\[\\]/BootstrapNodes = [\\\"$ENODE_ESC\\\"]/g\" /etc/geth/miner01/gethconfig.toml;
           sed -i \"s/BootstrapNodesV5 = \\[\\]/BootstrapNodesV5 = [\\\"$ENODE_ESC\\\"]/g\" /etc/geth/miner01/gethconfig.toml;
           /usr/local/bin/geth \
           --dashboard \
           --mine \
           --verbosity 3  \
           --unlock 0xc11ba4c7c24f70e7a581c7daa92eac108099acec --password /etc/testnet/miner01/password.txt --gasprice '0x0' --targetgaslimit '9000000000000'  \
           --config /etc/geth/miner01/gethconfig.toml;"
        ports:
          - containerPort: 8545
          - containerPort: 8546
            protocol: UDP
          - containerPort: 30303
        volumeMounts:
        - name: miner01-persistent-storage
          mountPath: /etc/testnet/miner01
        - name: miner01-config-persistent-storage
          mountPath: /etc/gethconfigmap/miner01
        - name: keystore-config-persistent-storage
          mountPath: /etc/testnet/miner01/keystore/UTC--2019-06-04T13-52-41.551926270Z--c11ba4c7c24f70e7a581c7daa92eac108099acec
          subPath: UTC--2019-06-04T13-52-41.551926270Z--c11ba4c7c24f70e7a581c7daa92eac108099acec
        - name: geth-boot-node-persistent-storage
          mountPath: /etc/testnet/bootnode
        - name: genesis-config-persistent-storage
          mountPath: /etc/geth/genesis/genesis-geth.json
          subPath: genesis-geth.json
      volumes:
      - name: keystore-config-persistent-storage
        configMap:
          name: keystore-config-miner01
          items:
          - key: UTC--2019-06-04T13-52-41.551926270Z--c11ba4c7c24f70e7a581c7daa92eac108099acec
            path: UTC--2019-06-04T13-52-41.551926270Z--c11ba4c7c24f70e7a581c7daa92eac108099acec
      - name: geth-boot-node-persistent-storage
        hostPath:
          path: /var/lib/docker/geth-storage/bootnode
      - name: genesis-config-persistent-storage
        configMap:
          name: genesis-config
          items:
          - key: genesis-geth.json
            path: genesis-geth.json
      - name: miner01-persistent-storage
        persistentVolumeClaim:
          claimName: volume-miner01
      - name: miner01-config-persistent-storage
        configMap:
          name: gethconfig-miner01
          items:
          - key: gethconfig
            path: gethconfig.toml

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  labels:
    app: miner
    tier: backend
    name: geth-miner02
  name: geth-miner02
spec:
  selector:
    matchLabels:
      app: miner
  replicas: 1
  serviceName: geth-miner02
  template:
    metadata:
      name: geth-miner02
      labels:
        app: miner
        tier: backend
        name: miner02
    spec:
      containers:
      - name: miner02-container
        image: ethereum/client-go:v1.8.27
        imagePullPolicy: Always
        command: [ "sh" ]
        args:
        - "-cx"
        - "/usr/local/bin/geth --datadir /etc/testnet/miner02 init /etc/geth/genesis/genesis-geth.json;
           touch /etc/testnet/miner02/genesis_created;
           echo 123 > /etc/testnet/miner02/password.txt;
           mkdir -p /etc/geth/miner02;
           cp /etc/gethconfigmap/miner02/gethconfig.toml /etc/geth/miner02;
           ENODE=$(cat /etc/testnet/bootnode/enode.address);
           ENODE_ESC=$(echo $ENODE | sed 's@//@\\\\/\\\\/@g');
           sed -i \"s/BootstrapNodes = \\[\\]/BootstrapNodes = [\\\"$ENODE_ESC\\\"]/g\" /etc/geth/miner02/gethconfig.toml;
           sed -i \"s/BootstrapNodesV5 = \\[\\]/BootstrapNodesV5 = [\\\"$ENODE_ESC\\\"]/g\" /etc/geth/miner02/gethconfig.toml;
           /usr/local/bin/geth \
           --dashboard \
           --mine \
           --verbosity 3  \
           --unlock 0x4c92786b90d848eaa3f4ef46918af724a309ae79 --password /etc/testnet/miner02/password.txt --gasprice '0x0' --targetgaslimit '9000000000000'  \
           --config /etc/geth/miner02/gethconfig.toml;"
        ports:
          - containerPort: 8545
          - containerPort: 8546
            protocol: UDP
          - containerPort: 30303
        volumeMounts:
        - name: miner02-persistent-storage
          mountPath: /etc/testnet/miner02
        - name: miner02-config-persistent-storage
          mountPath: /etc/gethconfigmap/miner02
        - name: keystore-config-persistent-storage
          mountPath: /etc/testnet/miner02/keystore/UTC--2019-06-04T13-52-48.511656735Z--4c92786b90d848eaa3f4ef46918af724a309ae79
          subPath: UTC--2019-06-04T13-52-48.511656735Z--4c92786b90d848eaa3f4ef46918af724a309ae79
        - name: geth-boot-node-persistent-storage
          mountPath: /etc/testnet/bootnode
        - name: genesis-config-persistent-storage
          mountPath: /etc/geth/genesis/genesis-geth.json
          subPath: genesis-geth.json
      volumes:
      - name: keystore-config-persistent-storage
        configMap:
          name: keystore-config-miner02
          items:
          - key: UTC--2019-06-04T13-52-48.511656735Z--4c92786b90d848eaa3f4ef46918af724a309ae79
            path: UTC--2019-06-04T13-52-48.511656735Z--4c92786b90d848eaa3f4ef46918af724a309ae79
      - name: geth-boot-node-persistent-storage
        hostPath:
          path: /var/lib/docker/geth-storage/bootnode
      - name: genesis-config-persistent-storage
        configMap:
          name: genesis-config
          items:
          - key: genesis-geth.json
            path: genesis-geth.json
      - name: miner02-persistent-storage
        persistentVolumeClaim:
          claimName: volume-miner02
      - name: miner02-config-persistent-storage
        configMap:
          name: gethconfig-miner02
          items:
          - key: gethconfig
            path: gethconfig.toml

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: default
  labels:
    app: miner
    tier: backend
    name: geth-miner03
  name: geth-miner03
spec:
  selector:
    matchLabels:
      app: miner
  replicas: 1
  serviceName: geth-miner03
  template:
    metadata:
      name: geth-miner03
      labels:
        app: miner
        tier: backend
        name: miner03
    spec:
      containers:
      - name: miner03-container
        image: ethereum/client-go:v1.8.27
        imagePullPolicy: Always
        command: [ "sh" ]
        args:
        - "-cx"
        - "/usr/local/bin/geth --datadir /etc/testnet/miner03 init /etc/geth/genesis/genesis-geth.json;
           touch /etc/testnet/miner03/genesis_created;
           echo 123 > /etc/testnet/miner03/password.txt;
           mkdir -p /etc/geth/miner03;
           cp /etc/gethconfigmap/miner03/gethconfig.toml /etc/geth/miner03;
           ENODE=$(cat /etc/testnet/bootnode/enode.address);
           ENODE_ESC=$(echo $ENODE | sed 's@//@\\\\/\\\\/@g');
           sed -i \"s/BootstrapNodes = \\[\\]/BootstrapNodes = [\\\"$ENODE_ESC\\\"]/g\" /etc/geth/miner03/gethconfig.toml;
           sed -i \"s/BootstrapNodesV5 = \\[\\]/BootstrapNodesV5 = [\\\"$ENODE_ESC\\\"]/g\" /etc/geth/miner03/gethconfig.toml;
           /usr/local/bin/geth \
           --dashboard \
           --mine \
           --verbosity 3  \
           --unlock 0x4e7afbdc9413eeb582b3f1be49d652fa714484da --password /etc/testnet/miner03/password.txt --gasprice '0x0' --targetgaslimit '9000000000000'  \
           --config /etc/geth/miner03/gethconfig.toml;"
        ports:
          - containerPort: 8545
          - containerPort: 8546
            protocol: UDP
          - containerPort: 30303
        volumeMounts:
        - name: miner03-persistent-storage
          mountPath: /etc/testnet/miner03
        - name: miner03-config-persistent-storage
          mountPath: /etc/gethconfigmap/miner03
        - name: keystore-config-persistent-storage
          mountPath: /etc/testnet/miner03/keystore/UTC--2019-06-04T13-52-53.567362092Z--4e7afbdc9413eeb582b3f1be49d652fa714484da
          subPath: UTC--2019-06-04T13-52-53.567362092Z--4e7afbdc9413eeb582b3f1be49d652fa714484da
        - name: geth-boot-node-persistent-storage
          mountPath: /etc/testnet/bootnode
        - name: genesis-config-persistent-storage
          mountPath: /etc/geth/genesis/genesis-geth.json
          subPath: genesis-geth.json
      volumes:
      - name: keystore-config-persistent-storage
        configMap:
          name: keystore-config-miner03
          items:
          - key: UTC--2019-06-04T13-52-53.567362092Z--4e7afbdc9413eeb582b3f1be49d652fa714484da
            path: UTC--2019-06-04T13-52-53.567362092Z--4e7afbdc9413eeb582b3f1be49d652fa714484da
      - name: geth-boot-node-persistent-storage
        hostPath:
          path: /var/lib/docker/geth-storage/bootnode
      - name: genesis-config-persistent-storage
        configMap:
          name: genesis-config
          items:
          - key: genesis-geth.json
            path: genesis-geth.json
      - name: miner03-persistent-storage
        persistentVolumeClaim:
          claimName: volume-miner03
      - name: miner03-config-persistent-storage
        configMap:
          name: gethconfig-miner03
          items:
          - key: gethconfig
            path: gethconfig.toml

