---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner01
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner02
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume-miner03
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 80Gi
status: {}
---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    name: volume-ethmonitor
  name: volume-ethmonitor
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: volume-mongodb
  name: volume-mongodb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
status: {}
---
